### PR TITLE
Migrate network policies to gardener-extensions

### PR DESCRIPTION
**Pull request by mvladev**
**What this PR does / why we need it**:

Migrate network policy e2e tests.

**Which issue(s) this PR fixes**:
Fixes # https://github.com/gardener/gardener/issues/1137

**Special notes for your reviewer**:

Is there a way to run tests as in [.test-defs](https://github.com/gardener/gardener/tree/bbdcc8b32a3051ae1e4abd1f2d982c9917753ada/.test-defs)?

**Release note**:

```improvement developer
e2e network policy tests are moved to individual providers.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Once #218 is merged you should be able to continue with this.

**Comment by rfranzke** [comment]
#218 is merged now, please rebase and finish the PR.

**Comment by mvladev** [comment]
Rebased and tests are passing for all providers.

What's missing is a way to run them via CI

**Comment by rfranzke** [comment]
@mvladev the tests are failing. Always run `make verify` before pushing. Can you please fix them?

**Comment by mvladev** [comment]
@rfranzke had to disable tests from `./hack/tests.sh`

**Comment by rfranzke** [comment]
@mvladev can you please check why the publish step is still failing? Also, now that you're excluding the netpol tests from `make test`, can you create a separate script/rule that runs them?

**Comment by rfranzke** [comment]
ping

**Comment by mvladev** [comment]
I've no idea why it cannot find the missing package. It there in the commit.

**Comment by rfranzke** [comment]
Then please find out. Does it happen locally as well when running `make generate`?

**Comment by ialidzhikov** [comment]
Locally checked `make verify` - it was ok.
Let's see `concourse-ci/publish` after rebase.

**Comment by vpnachev** [comment]
@mvladev could clean up the leftovers of `dep`?

**Comment by mvladev** [comment]
@rfranzke have a look at it again. I've added some missing paths in `.dockerignore`

**Comment by rfranzke** [comment]
Now that this one is merged, can you please create a follow-up PR on gardener to remove the network policy tests there?

**Pull request merged**
