### PR TITLE
Split calico chart files

### LINKED ISSUE #439: Clean up kubernetes.io/cluster-service from calico extension
`kubernetes.io/cluster-service` is deprecated label by addon-manager. Now it is used only by kubectl for `cluster-info` command and it is respected only for `kind: Service` - kubernetes/kubernetes#72757 and gardener/gardener#997.
We could clean up this label from the calico chart for all non `kind: Service`s.

/kind flake

### LINKED ISSUE #462: Split calico chart to separate template files
#432 puts different resources in single files which is against to one of the helm chart recommendations that each resource definition should be in its own template file. Ref https://helm.sh/docs/topics/chart_best_practices/templates/.

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
Split calico chart files and clean up the label `kubernetes.io/cluster-service`

**Which issue(s) this PR fixes**:
Fixes #462, fixes #439 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by zanetworker** [comment]
@vpnachev do you think it makes sense to keep a layer of abstraction on top? otherwise with every new resource / change we add another file(s). For example, we can have RBAC, CRDs, Config, Deployment or something like that, wdyt?

**Comment by vpnachev** [comment]
The only option I see is to split this charto it into multiple sub-charts, but the structure will be the same as it is now. So I do not see any pros at the moment.

**Comment by rfranzke** [comment]
+1 for how got done by @vpnachev. It's way more clear to have a dedicated file per resource.

**Comment by zanetworker** [comment]
@rfranzke do we follow this pattern everywhere / should we?

**Comment by rfranzke** [comment]
We don't follow it everywhere, unfortunately, but we can introduce it as "convention" for new charts, at least, and refactor existing ones when we have to touch them anyways.

**Review by zanetworker — DISMISSED** [review]

**Comment by rfranzke** [comment]
Can we first merge #460 and then rebase this one on top?

**Comment by zanetworker** [comment]
sure, then let's hold it for now.

**Comment by rfranzke** [comment]
#460 is merged - can you rebase, please?

**Comment by rfranzke** [comment]
Can we prefix the filenames with the Kubernetes resource kind?

`deployment-<...>`

If you want to group certain resources belonging to a component together use folders:

```
templates
  - calico-node
    - daemonset-calico-node.yaml
    - configmap-<...>
  - calico-typha
    - ...
```

**Comment by rfranzke** [comment]
@zanetworker @DockToFuture ready for review

**Comment by vpnachev** [comment]
Done, I have switched from suffixes to prefixes.

**Review by zanetworker — APPROVED** [review]
Yosh, just spun up a cluster, everything looks good.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
