### PR TITLE
Reduce limits for control plane components for which VPA is deployed

### PR DESCRIPTION
**Pull request by ggaurav10**
**What this PR does / why we need it**:
Reduce limits for control plane components for which VPA is deployed. The `limits` are now controlled by VPA in its version 0.6+

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by rfranzke** [comment]
"WIP" because?

**Comment by ggaurav10** [comment]
> "WIP" because?

We are running perf tests, and we may see changes in the current numbers. I will remove the WIP label once we are done with the tests

**Comment by rfranzke** [comment]
OK, why do we need the PR then already now? See also https://github.com/gardener/documentation/pull/55.

**Comment by ggaurav10** [comment]
ah ok. Thanks for pointing this out. Will close it for now, and reopen when done.

**Comment by rfranzke** [comment]
@ggaurav10 notified me via Slack that the PR can is ready and can be reopened.

**Pull request merged**
