### PR TITLE
bastion host related ssh rules removed

### PR DESCRIPTION
**Pull request by ThormaehlenFred**
**What this PR does / why we need it**:
Bastion host related ssh rules removed

**Which issue(s) this PR fixes**:
Fixes: https://github.com/gardener/gardener-extensions/issues/343

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
I guess this changes affects `gardenctl ssh` on aws, right?

**Comment by rfranzke** [comment]
No, according to @DockToFuture gardenctl does already create its own security group and no longer relies on this one.

**Comment by ialidzhikov** [comment]
There are still some bastion related resources in our `main.tf`:
```
resource "aws_iam_role" "bastions" {

resource "aws_iam_instance_profile" "bastions" {

resource "aws_iam_role_policy" "bastions" {
```

**Comment by rfranzke** [comment]
Yes, on purpose for now. We can either keep them (to allow easier operations and less code in gardenctl), or we drop them and maybe add them to gardenctl? No strong opinion here.

**Comment by ialidzhikov** [comment]
I think we can move them to g/gardenctl in future. Currently provider-aws creates iam resources to allow gardenctl to potentially use them at some point in the time.

**Pull request merged**
