### PR TITLE
Fix Alicloud image vector handling in control plane actuator

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
Resolves the workaround introduced by https://github.com/gardener/gardener-extensions/commit/c2da1605cfe8169375598f6df918e0e0d7717850 for Alicloud due to missing image vector functionality.

**Special notes for your reviewer**:
🚧  Depends on https://github.com/gardener/gardener/pull/1243 to be merged. After that we need to cherry-pick this commit to the `gardener-extensions-fixes` branch and then revendor.

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by jia-jerry** [comment]
@rfranzke , need to run hack/generate.sh...

**Comment by jia-jerry** [comment]
@EmoinLanyu

**Review by jia-jerry — DISMISSED** [review]
/lgtm . except unit tests

**Comment by rfranzke** [comment]
Thanks, I revendored and merged now. I also tested with Alicloud 1.13, 1.14, 1.15.

**Pull request merged**
