### PR TITLE
Switch to go modules

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
The PR adopts go modules to manage the vendor folder in gardener/gardener-extensions and to define go.mod module files.

The following updates are also included:
`github.com/onsi/ginkgo` -> `v1.8.0`
`github.com/onsi/gomega` -> `v1.5.0`

**Which issue(s) this PR fixes**:
Ref gardener/gardener#1096.

**Special notes for your reviewer**:

**Release note**:

```improvement operator
`dep` is replaced by `go mod`. `github.com/gardener/gardener-extensions` now publishes go module files containing dependency version information.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Thanks, can you please check why https://concourse.ci.infra.gardener.cloud/builds/37410 is failing?

**Comment by ialidzhikov** [comment]
Nice catch by `hack/check.sh`. Updated the PR.

**Comment by rfranzke** [comment]
Please rebase

**Comment by ialidzhikov** [comment]
Rebased

**Comment by ialidzhikov** [comment]
Updated the PR.

**Pull request merged**
