### PR TITLE
Do Not Merge

### PR DESCRIPTION
**Pull request by ggaurav10**
build for perf test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
You can build it  locally, right? Is there any issue that prevents you to do that?

**Comment by ggaurav10** [comment]
The build process erred out with following message:
```
Install
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
make: *** [Makefile:62: install] Error 1
```
Not enough free memory to build locally.

**Comment by ialidzhikov** [comment]
Did you tried to increase the Docker resources? I have no issues with 4 CPUs and 5GB memory.

**Comment by ggaurav10** [comment]
Closing the PR
Thanks for the suggestion @ialidzhikov

**Comment by ialidzhikov** [comment]
Let us know whether the resource increase resolves the issue for you.

**Comment by ggaurav10** [comment]
Yes it did :)

**Pull request closed without merging**
