### PR TITLE
(WIP): Add Support for Cilium Networking

### PR DESCRIPTION
**Pull request by soumynathan**
This is a Work In Progress PR.(DO NOT MERGE)
Add Cilium Networking as an additional Network-extension to
gardener-extensions.
Cilium is open source software for transparently securing the network
connectivity between application services deployed using Linux container
management platforms like Docker and Kubernetes that depends on the new
Linux kernel technology called BPF.

Fixes: #129
Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>

### CODE REVIEW

**Comment by zanetworker** [comment]
Hi @soumynathan, 

Thank you for starting to work on this! 

I see that this is a WIP, for reference we already have the Calico extension so you could use it to get an intuition on how we template our charts, file structure, versions, and so on. Here are a few examples: 

- https://github.com/gardener/gardener-extensions/tree/master/controllers/networking-calico/charts/internal/calico/templates 
- https://github.com/gardener/gardener-extensions/tree/master/controllers/networking-calico/charts/internal/calico/templates

And let us know if you have questions.

**Comment by soumynathan** [comment]
> Hi @soumynathan,
> 
> Thank you for starting to work on this!
> 
> I see that this is a WIP, for reference we already have the Calico extension so you could use it to get an intuition on how we template our charts, file structure, versions, and so on. Here are a few examples:
> 
> * https://github.com/gardener/gardener-extensions/tree/master/controllers/networking-calico/charts/internal/calico/templates
> * https://github.com/gardener/gardener-extensions/tree/master/controllers/networking-calico/charts/internal/calico/templates
> 
> And let us know if you have questions.
Sure I have been looking into the calico-templates already. But I was not sure about the internal folder naming structure and the details. So just started so that if I can get some early reviews as an when I add details to this. ( While I work on getting my development environment, I want to learn and code in parallel.) Hope this helps.

**Comment by zanetworker** [comment]
Maybe we can also add the hubble chart https://github.com/cilium/hubble/tree/master/install/kubernetes/hubble/templates ?

**Comment by rfranzke** [comment]
How do we proceed with this PR? So far, there are only the charts added but no controller code.

**Comment by soumynathan** [comment]
> How do we proceed with this PR? So far, there are only the charts added but no controller code.

Yes this is a Work in Progress and we are working on a plan to complete it. If you have any further questions please let me knwo.

**Comment by rfranzke** [comment]
@soumynathan we have moved the Calico controller to a dedicated repository: https://github.com/gardener/gardener-extension-networking-calico

Similarly, we have created a repository for Cilium: https://github.com/gardener/gardener-extension-networking-cilium

Would you please create the PR there? Thank you :)

**Pull request closed without merging**
